#!/bin/bash

# Configuration
########################################################

# Where activate script of your virtual environment is located
DJANGO_ENV=~/DojoAssignments/Python/myEnvironments/Django/bin/activate

########################################################
# ONLY CHANGE IF NECESSARY
# Where libs folder of this script is located
DJANGO_LIBS=${BASH_SOURCE%/*}/django-proj-libs # Default is same level as this script

########################################################

if [ ${PWD##*/} != "apps" ]
then
    echo "Must be in project apps folder"
    exit 1
fi

if ["$VIRTUAL_ENV" != "" ]
then
    deactivate
fi

source $DJANGO_ENV
python ../manage.py startapp $1 &&

echo "Created base files for $1"

cd ../

PROJ=${PWD##*/}

sed -i "/INSTALLED_APPS/a \ \ \ \ 'apps.$1'," $PROJ/settings.py
sed -i "/urlpatterns/a \ \ \ \ url(r'^$1/', include('apps.$1.urls'))," $PROJ/urls.py

echo "Linked $1 with parent project urls and settings"

cd apps/$1

touch urls.py
$DJANGO_LIBS/app_urls urls.py
$DJANGO_LIBS/views views.py $1

mkdir -p static/$1/{css,js,img}
mkdir -p templates/$1

touch static/$1/css/main.css

$DJANGO_LIBS/html templates/$1/index.html $1

echo "Created static and template base files"

