#!/bin/bash

# Configuration, use correct paths!
##################################################################
# Where the project should be created
DJANGO_PATH=~/DojoAssignments/Python/Django 

# Where the activate script of your virtual environment is located
DJANGO_ENVIRONMENT=~/DojoAssignments/Python/myEnvironments/Django/bin/activate

##################################################################
# ONLY CHANGE IF NECESSARY
# Where the libs folder of this script is located
DJANGO_LIBS=${BASH_SOURCE%/*}/django-proj-libs # default is same level of this script

##################################################################

PROJECT=$1
APP=$2
APP_LOCATION='apps.$APP'

if [["$VIRTUAL_ENV" != "" ]]
then
    deactivate
fi

cd $DJANGO_PATH
source $DJANGO_ENVIRONMENT

django-admin startproject $PROJECT
echo "Started Django project $PROJECT"

mkdir $DJANGO_PATH/$PROJECT/apps

cd $PROJECT/apps

python ../manage.py startapp $APP
echo "Started Django app $APP"

touch __init__.py

touch $APP/urls.py

$DJANGO_LIBS/app_urls $APP/urls.py

sed -i "/INSTALLED_APPS/a \ \ \ \ 'apps.$APP'," $DJANGO_PATH/$PROJECT/$PROJECT/settings.py

$DJANGO_LIBS/proj_urls $DJANGO_PATH/$PROJECT/$PROJECT/urls.py $APP

cd $APP

mkdir -p static/$APP/css
mkdir static/$APP/js
mkdir static/$APP/img
mkdir -p templates/$APP

touch static/$APP/css/main.css

touch templates/$APP/index.html

$DJANGO_LIBS/html templates/$APP/index.html $APP

$DJANGO_LIBS/views views.py $APP
echo "Configured and linked Django app to project"

cd ../../
python manage.py makemigrations
python manage.py migrate
